---

before_script:
    - export BUILD_NUMBER=${CI_COMMIT_REF_NAME}
    - if [ ${CI_COMMIT_REF_NAME} == 'master' ] ; then export BUILD_NUMBER=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:8}; fi
    - echo ${BUILD_NUMBER}


stages:
  - build
  - package
  - repo

build:
  stage: build
  tags:
    - docker
  image: golang
  script:
  - wget -qO - https://packages.confluent.io/deb/4.1/archive.key | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
  - apt-get update
  - apt-get install -y confluent-platform-oss-2.11
  - make -f mk/Makefile  "go build"
  - ls -alh
  - tree
  artifacts:
    paths:
      - bin/

package:
  stage: package
  tags:
    - docker
  image: dockerfile/fpm
  script:
  - echo "do packaginf eith fpm"
  dependencies:
   - build

upload_deb:
  stage: repo
  tags:
    - bash
  only:
    - master
  script:
    - echo "Deploying ${BUILD_NUMBER} with aptly"
  when: manual
